envTest:envTest.cpp 
	gcc -g $^ -o $@
testOrphans:testOrphans.cpp 
	gcc -g $^ -o $@
testJiangshi:testjiangshi.cpp
	gcc -g $^ -o $@


jindutiao:jindutiao.c
	gcc -g  $^ -o $@
a:a.c
	gcc $^ -o $@
orphans:orphans.c
	gcc $^ -o $@
fork:createprogress.c
	gcc $^ -o $@

test:test.c
	gcc $^ -o $@
